### ISSUE TITLE
新版的libclang在我的windows10机器上无法加载

### ISSUE THREAD

**Issue by 1bool** [snakeleon/YouCompleteMe-x64#6]
![屏幕截图 2021-10-14 191722](https://user-images.githubusercontent.com/751820/137307894-ded75eba-3bcf-41a0-bda3-6099192588e8.png)

**Comment by snakeleon** [comment]
是不是你的环境缺少MS VCRuntime库文件
![图片](https://user-images.githubusercontent.com/10704516/137456664-1bfaa389-ae02-45e4-b3da-59346fd05a40.png)
ycm_core.pyd的依赖只有这几个文件

![图片](https://user-images.githubusercontent.com/10704516/137457158-d815ca4d-c665-4acc-888c-8acf2b83930e.png)
那么libclang.dll的依赖是这些，检查是不是缺少MS VCRuntime库文件(这里依赖MSVCP140.dll，VCRUNTIME140.dll)
查找下载 VC运行库合集Visual C++ Runtime Installer (All-In-One ）安装可以解决。
